# 5.6, а не latest, потому с 8 версии нужно подключать плагин
# mysql_native_password - https://www.php.net/manual/en/ref.pdo-mysql.php
# для упрощения работы стартонул с привычной 5.6
FROM mysql:5.6
ENV MYSQL_ROOT_PASSWORD=12345678